### ISSUE TITLE
Issues in test_count_passenger

### ISSUE THREAD

**Issue by MaazJamal** [MaazJamal/elevator_simulator#41]
https://github.com/MaazJamal/elevator_simulator/blob/d8885af5fa7ec969b13c9d388d7882021dcf22c6/test/test_count_passenger.c#L1
There is missing include of "count_passenger.h"

The compiler is warning that "note: 'sprintf' output between 124 and 134 bytes into a destination of size 100" so we need to increase the size of char array.

**Comment by MaazJamal** [comment]
https://github.com/MaazJamal/elevator_simulator/blob/d8885af5fa7ec969b13c9d388d7882021dcf22c6/test/test_count_passenger.c#L185
The count_passengers should be loaded from the .h files not redefined here. This needs to be removed

**Comment by Hariprasadm1408** [comment]
Issue fixed. Made the functions as static in test_function
